version: '3.8'
services:
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "PasswordThunders123"
      MSSQL_PID: "Express"
    ports:
      - "1433:1433"

  server:
    image: thunders-api
    build:
      context: .
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=db;Database=ThundersDb;User=sa;Password=PasswordThunders123;TrustServerCertificate=True
    ports:
      - "5050:8080"
      - "5051:8081"